server:
    port: 8003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/device_service
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        dll-auto: update