server:
  port: 8002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: root
    hikari:
      data-source-class-name: org.postgresql.ds.PGSimpleDataSource
      maximum-pool-size: 5
      connection-timeout: 30000 # default
      max-lifetime: 1800000 # 30 minutes

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        dll-auto: update
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/user_service
    user: postgres
    password: root